name: autoquill_ai
description: "Audio transcription desktop app"
publish_to: 'none'
version: 1.5.0+8

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^9.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  equatable: ^2.0.5
  path_provider: ^2.1.1
  get_it: ^7.6.4
  record: ^5.0.4
  just_audio: ^0.9.36
  http: ^1.3.0
  hotkey_manager: ^0.2.3
  bot_toast: ^4.0.1
  desktop_multi_window: ^0.2.1
  pasteboard: ^0.4.0
  keypress_simulator: ^0.2.0
  clipboard_watcher: ^0.3.0
  path: ^1.8.3
  window_manager: ^0.4.3
  url_launcher: ^6.2.5
  lottie: ^3.1.0
  screen_capturer: ^0.2.3
  auto_updater: ^1.0.0
  volume_controller: ^3.4.0
  tray_manager: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/icons/with_bg/
    - assets/sounds/
    
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/with_bg/AQOL.png"
  remove_alpha_ios: true
  macos:
    generate: true
    image_path: "assets/icons/with_bg/AQOL.png"
